<a href="https://colab.research.google.com/github/retutux-arch/Python_Data_Science_practica/blob/main/vamos_a_practicar_Pandas_conociendo_la_biblioteca_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practica biblitecas Pandas**

1. ***Importa el archivo
alumnos.csv y almacena su contenido en un DataFrame de Pandas.***

In [2]:
import pandas as pd

url = 'https://gist.githubusercontent.com/ahcamachod/807a2c1cf6c19108b2b701ea1791ab45/raw/fb84f8b2d8917a89de26679eccdbc8f9c1d2e933/alumnos.csv'
datos_alumnos = pd.read_csv(url)
datos_alumnos

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   NaN      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   NaN      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   NaN      False
10    Danilo    21   NaN      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   NaN      False
15    Milena    29   7.0       True
16     Lucas    33   NaN      False
17     Nadia    34   8.0  Verdadero

2. ***Visualiza las primeras 7
filas del DataFrame y las últimas 5.***

In [4]:
datos_alumnos.head(7)

    Nombre  Edad  Nota Aprobado
0  Alberto    20   7.5     True
1      Ana    18   NaN    False
2   Camila    27   2.5    False
3    David    18   5.0    False
4    Brian    21  10.0     True
5    Bruna    23   NaN    False
6  Daniela    21   7.0     True

In [9]:
datos_alumnos.tail()

    Nombre  Edad  Nota   Aprobado
13  Miriam    25   9.0       True
14   Pablo    37   NaN      False
15  Milena    29   7.0       True
16   Lucas    33   NaN      False
17   Nadia    34   8.0  Verdadero

3. ***Verifica la cantidad de filas y columnas en este DataFrame.***

In [6]:
datos_alumnos.shape

(18, 4)

4. ***Explora las columnas del DataFrame y analiza los tipos de datos presentes en cada columna.***

In [10]:
datos_alumnos['Nombre']

0      Alberto
1          Ana
2       Camila
3        David
4        Brian
5        Bruna
6      Daniela
7       Carlos
8       Alicia
9       Victor
10      Danilo
11     Ignacio
12    Stephany
13      Miriam
14       Pablo
15      Milena
16       Lucas
17       Nadia
Name: Nombre, dtype: object

In [11]:
datos_alumnos[['Edad', 'Nota']]

    Edad  Nota
0     20   7.5
1     18   NaN
2     27   2.5
3     18   5.0
4     21  10.0
5     23   NaN
6     21   7.0
7     19   6.0
8     35   5.6
9     28   NaN
10    21   NaN
11    24   4.5
12    26  10.0
13    25   9.0
14    37   NaN
15    29   7.0
16    33   NaN
17    34   8.0

In [12]:
datos_alumnos.dtypes

Nombre       object
Edad          int64
Nota        float64
Aprobado     object
dtype: object

In [13]:
datos_alumnos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    18 non-null     object
 1   Edad      18 non-null     int64
 2   Nota      12 non-null     float64
 3   Aprobado  18 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 708.0+ bytes

***Extra: Calcula algunas estadísticas descriptivas básicas de los datos en el DataFrame (media, desviación estándar, etc.). Pista: busca el método "describe".***

In [16]:
datos_alumnos.describe()

            Edad       Nota
count  18.000000  12.000000
mean   25.500000   6.841667
std     6.070662   2.264532
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000

In [15]:
datos_alumnos.describe(include='all')

         Nombre       Edad       Nota Aprobado
count        18  18.000000  12.000000       18
unique       18        NaN        NaN        3
top     Alberto        NaN        NaN    False
freq          1        NaN        NaN       11
mean        NaN  25.500000   6.841667      NaN
std         NaN   6.070662   2.264532      NaN
min         NaN  18.000000   2.500000      NaN
25%         NaN  21.000000   5.450000      NaN
50%         NaN  24.500000   7.000000      NaN
75%         NaN  28.750000   8.250000      NaN
max         NaN  37.000000  10.000000      NaN