<a href="https://colab.research.google.com/github/retutux-arch/Python_Data_Science_practica/blob/main/vamos_a_practicar_Pandas_conociendo_la_biblioteca_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practica biblitecas Pandas**

## **1. Importa el archivo alumnos.csv y almacena su contenido en un DataFrame de Pandas.**

In [2]:
import pandas as pd

url = 'https://gist.githubusercontent.com/ahcamachod/807a2c1cf6c19108b2b701ea1791ab45/raw/fb84f8b2d8917a89de26679eccdbc8f9c1d2e933/alumnos.csv'
datos_alumnos = pd.read_csv(url)
datos_alumnos

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   NaN      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   NaN      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   NaN      False
10    Danilo    21   NaN      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   NaN      False
15    Milena    29   7.0       True
16     Lucas    33   NaN      False
17     Nadia    34   8.0  Verdadero

## 2.**Visualiza las primeras 7 filas del DataFrame y las últimas 5.**

In [3]:
datos_alumnos.head(7)

    Nombre  Edad  Nota Aprobado
0  Alberto    20   7.5     True
1      Ana    18   NaN    False
2   Camila    27   2.5    False
3    David    18   5.0    False
4    Brian    21  10.0     True
5    Bruna    23   NaN    False
6  Daniela    21   7.0     True

In [4]:
datos_alumnos.tail()

    Nombre  Edad  Nota   Aprobado
13  Miriam    25   9.0       True
14   Pablo    37   NaN      False
15  Milena    29   7.0       True
16   Lucas    33   NaN      False
17   Nadia    34   8.0  Verdadero

## 3. **Verifica la cantidad de filas y columnas en este DataFrame.**

In [5]:
datos_alumnos.shape

(18, 4)

## 4. **Explora las columnas del DataFrame y analiza los tipos de datos presentes en cada columna.**

In [6]:
datos_alumnos['Nombre']

0      Alberto
1          Ana
2       Camila
3        David
4        Brian
5        Bruna
6      Daniela
7       Carlos
8       Alicia
9       Victor
10      Danilo
11     Ignacio
12    Stephany
13      Miriam
14       Pablo
15      Milena
16       Lucas
17       Nadia
Name: Nombre, dtype: object

In [7]:
datos_alumnos[['Edad', 'Nota']]

    Edad  Nota
0     20   7.5
1     18   NaN
2     27   2.5
3     18   5.0
4     21  10.0
5     23   NaN
6     21   7.0
7     19   6.0
8     35   5.6
9     28   NaN
10    21   NaN
11    24   4.5
12    26  10.0
13    25   9.0
14    37   NaN
15    29   7.0
16    33   NaN
17    34   8.0

In [8]:
datos_alumnos.dtypes

Nombre       object
Edad          int64
Nota        float64
Aprobado     object
dtype: object

In [9]:
datos_alumnos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    18 non-null     object
 1   Edad      18 non-null     int64
 2   Nota      12 non-null     float64
 3   Aprobado  18 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 708.0+ bytes

## ***Extra: Calcula algunas estadísticas descriptivas básicas de los datos en el DataFrame (media, desviación estándar, etc.). Pista: busca el método "describe".***

In [10]:
datos_alumnos.describe()

            Edad       Nota
count  18.000000  12.000000
mean   25.500000   6.841667
std     6.070662   2.264532
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000

In [11]:
datos_alumnos.describe(include='all')

         Nombre       Edad       Nota Aprobado
count        18  18.000000  12.000000       18
unique       18        NaN        NaN        3
top     Alberto        NaN        NaN    False
freq          1        NaN        NaN       11
mean        NaN  25.500000   6.841667      NaN
std         NaN   6.070662   2.264532      NaN
min         NaN  18.000000   2.500000      NaN
25%         NaN  21.000000   5.450000      NaN
50%         NaN  24.500000   7.000000      NaN
75%         NaN  28.750000   8.250000      NaN
max         NaN  37.000000  10.000000      NaN

#  **Practica biblitecas Pandas 2.1**

## **1. Verifica si la base de datos contiene datos nulos y, en caso de tenerlos, realiza el tratamiento de estos datos nulos de la manera que consideres más coherente con la situación.**

In [12]:
datos_alumnos.isnull().sum()

Nombre      0
Edad        0
Nota        6
Aprobado    0
dtype: int64

In [13]:
datos_alumnos.fillna(0, inplace=True)
datos_alumnos.isnull().sum()

Nombre      0
Edad        0
Nota        0
Aprobado    0
dtype: int64

In [14]:
datos_alumnos

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   0.0      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   0.0      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   0.0      False
10    Danilo    21   0.0      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   0.0      False
15    Milena    29   7.0       True
16     Lucas    33   0.0      False
17     Nadia    34   8.0  Verdadero

## **2. Los estudiantes "Alicia" y "Carlos" ya no forman parte del grupo. Por lo tanto, elimínalos de la base de datos.**

In [15]:
datos_alumnos.query('Nombre == "Alicia" or Nombre == "Carlos"')

   Nombre  Edad  Nota Aprobado
7  Carlos    19   6.0    False
8  Alicia    35   5.6    False

In [16]:
datos_alumnos.drop(datos_alumnos.query('Nombre == "Alicia" or Nombre == "Carlos"').index, inplace=True)
datos_alumnos.query('Nombre == "Alicia" or Nombre == "Carlos"')

Empty DataFrame
Columns: [Nombre, Edad, Nota, Aprobado]
Index: []

## **3. Aplica un filtro que seleccione solo a los estudiantes que fueron aprobados.**

In [17]:
datos_alumnos

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   0.0      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   0.0      False
6    Daniela    21   7.0       True
9     Victor    28   0.0      False
10    Danilo    21   0.0      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   0.0      False
15    Milena    29   7.0       True
16     Lucas    33   0.0      False
17     Nadia    34   8.0  Verdadero

In [18]:
# El filtro esta correcto, pero la columna "Aprobados" no es consistente
# ya que todos los valores son objetos en lugar de booleanos
df_alumnos_aprobados = datos_alumnos.query('Aprobado == True')
df_alumnos_aprobados

Empty DataFrame
Columns: [Nombre, Edad, Nota, Aprobado]
Index: []

In [19]:
datos_alumnos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    16 non-null     object
 1   Edad      16 non-null     int64
 2   Nota      16 non-null     float64
 3   Aprobado  16 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 640.0+ bytes

In [20]:
# con el metodo ".eplace" cambiamos Verdadero por True
datos_alumnos['Aprobado'] = datos_alumnos['Aprobado'].replace('Verdadero', True)
#
#datos_alumnos.loc[datos_alumnos['Aprobado'] == 'Verdadero', 'Aprobado'] = True

In [21]:
# Los datos de la columna "Aprobados son objetos no bool, por lo cual reguilarizamos"
# Aseguramos que la columna 'Aprobado' sea de tipo string para un mapeo consistente
datos_alumnos['Aprobado'] = datos_alumnos['Aprobado'].astype(str)

# Definimos un diccionario de mapeo para convertir strings a booleanos
# Esto manejará 'Verdadero', 'True' y 'False' correctamente
conversion_map = {
    'Verdadero': True,
    'True': True,
    'False': False
}

# Aplicamos el mapeo a la columna 'Aprobado'
datos_alumnos['Aprobado'] = datos_alumnos['Aprobado'].map(conversion_map)

# Ahora, convertimos explícitamente la columna a tipo booleano.
# Esto es importante para asegurar que Pandas la reconozca como 'bool' y no 'object'.
datos_alumnos['Aprobado'] = datos_alumnos['Aprobado'].astype(bool)

# Filtramos solo a los estudiantes que fueron aprobados
df_alumnos_aprobados = datos_alumnos.loc[datos_alumnos['Aprobado'] == True]

# Mostramos el DataFrame filtrado y el tipo de dato de la columna 'Aprobado' para verificar
display(df_alumnos_aprobados)
display(datos_alumnos['Aprobado'].dtypes)

      Nombre  Edad  Nota  Aprobado
0    Alberto    20   7.5      True
4      Brian    21  10.0      True
6    Daniela    21   7.0      True
12  Stephany    26  10.0      True
13    Miriam    25   9.0      True
15    Milena    29   7.0      True
17     Nadia    34   8.0      True

dtype('bool')

In [22]:
# object a bool
datos_alumnos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    16 non-null     object
 1   Edad      16 non-null     int64
 2   Nota      16 non-null     float64
 3   Aprobado  16 non-null     bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 528.0+ bytes

In [23]:
# Filtro operando
df_alumnos_aprobados

      Nombre  Edad  Nota  Aprobado
0    Alberto    20   7.5      True
4      Brian    21  10.0      True
6    Daniela    21   7.0      True
12  Stephany    26  10.0      True
13    Miriam    25   9.0      True
15    Milena    29   7.0      True
17     Nadia    34   8.0      True

In [24]:
# con "reset._index" reemplazmos los indices numericos para mejor
# legibilidad y manejo futuro
df_alumnos_aprobados = df_alumnos_aprobados.reset_index(drop=True)
df_alumnos_aprobados

     Nombre  Edad  Nota  Aprobado
0   Alberto    20   7.5      True
1     Brian    21  10.0      True
2   Daniela    21   7.0      True
3  Stephany    26  10.0      True
4    Miriam    25   9.0      True
5    Milena    29   7.0      True
6     Nadia    34   8.0      True

## **4.Guarda el DataFrame que contiene solo a los estudiantes aprobados en un archivo CSV llamado "alumnos_aprobados.csv".**

In [25]:
df_alumnos_aprobados.to_csv('alumnos_aprobados.csv', index=False)

In [26]:
pd.read_csv('alumnos_aprobados.csv')

     Nombre  Edad  Nota  Aprobado
0   Alberto    20   7.5      True
1     Brian    21  10.0      True
2   Daniela    21   7.0      True
3  Stephany    26  10.0      True
4    Miriam    25   9.0      True
5    Milena    29   7.0      True
6     Nadia    34   8.0      True

In [27]:
# Se resplada en mi drive.
df_alumnos_aprobados.to_csv('/content/drive/MyDrive/Pandas/alumnos_aprobados.csv', index=False)

## ***Extra***: **Al revisar las calificaciones de los estudiantes aprobados, notamos que algunas calificaciones eran incorrectas. Las estudiantes que obtuvieron una calificación de 7.0, en realidad tenían un punto extra que no se contabilizó. Por lo tanto, reemplaza las calificaciones de 7.0 en la base de datos por 8.0. Consejo: busca el método replace.**

In [28]:
# Reemplazamos las calificaciones de 7.0 por 8.0 en la columna 'Nota' del DataFrame original 'datos_alumnos'
datos_alumnos['Nota'] = datos_alumnos['Nota'].replace(7.0, 8.0)

# Mostramos el DataFrame para verificar los cambios
display(datos_alumnos)

      Nombre  Edad  Nota  Aprobado
0    Alberto    20   7.5      True
1        Ana    18   0.0     False
2     Camila    27   2.5     False
3      David    18   5.0     False
4      Brian    21  10.0      True
5      Bruna    23   0.0     False
6    Daniela    21   8.0      True
9     Victor    28   0.0     False
10    Danilo    21   0.0     False
11   Ignacio    24   4.5     False
12  Stephany    26  10.0      True
13    Miriam    25   9.0      True
14     Pablo    37   0.0     False
15    Milena    29   8.0      True
16     Lucas    33   0.0     False
17     Nadia    34   8.0      True

#  **Practica biblitecas Pandas 2.2**

## **1. Los estudiantes participaron en una actividad extracurricular y ganaron puntos extras. Estos puntos extras corresponden al 40% de su nota actual. Por lo tanto, crea una columna llamada "Puntos_extras" que contenga los puntos extras de cada estudiante, es decir, el 40% de su nota actual.**

In [30]:
datos_alumnos['Puntos_extras'] = datos_alumnos['Nota'] * 0.4
datos_alumnos

      Nombre  Edad  Nota  Aprobado  Puntos_extras
0    Alberto    20   7.5      True            3.0
1        Ana    18   0.0     False            0.0
2     Camila    27   2.5     False            1.0
3      David    18   5.0     False            2.0
4      Brian    21  10.0      True            4.0
5      Bruna    23   0.0     False            0.0
6    Daniela    21   8.0      True            3.2
9     Victor    28   0.0     False            0.0
10    Danilo    21   0.0     False            0.0
11   Ignacio    24   4.5     False            1.8
12  Stephany    26  10.0      True            4.0
13    Miriam    25   9.0      True            3.6
14     Pablo    37   0.0     False            0.0
15    Milena    29   8.0      True            3.2
16     Lucas    33   0.0     False            0.0
17     Nadia    34   8.0      True            3.2

## **2. Crea otra columna llamada "Notas_finales" que contenga las notas de cada estudiante sumadas con los puntos extras.**

In [33]:
datos_alumnos['Notas_finales'] = datos_alumnos['Nota'] + datos_alumnos['Puntos_extras']
datos_alumnos

      Nombre  Edad  Nota  Aprobado  Puntos_extras  Notas_finales
0    Alberto    20   7.5      True            3.0           10.5
1        Ana    18   0.0     False            0.0            0.0
2     Camila    27   2.5     False            1.0            3.5
3      David    18   5.0     False            2.0            7.0
4      Brian    21  10.0      True            4.0           14.0
5      Bruna    23   0.0     False            0.0            0.0
6    Daniela    21   8.0      True            3.2           11.2
9     Victor    28   0.0     False            0.0            0.0
10    Danilo    21   0.0     False            0.0            0.0
11   Ignacio    24   4.5     False            1.8            6.3
12  Stephany    26  10.0      True            4.0           14.0
13    Miriam    25   9.0      True            3.6           12.6
14     Pablo    37   0.0     False            0.0            0.0
15    Milena    29   8.0      True            3.2           11.2
16     Lucas    33   0.0     False            0.0            0.0
17     Nadia    34   8.0      True            3.2           11.2

## **3. Dado que hubo una puntuación extra, algunos estudiantes que no habían sido aprobados antes pueden haber sido aprobados ahora. En función de esto, crea una columna llamada "Aprobado_final" con los siguientes valores:**


* ***True: si el estudiante está aprobado (la nota final debe ser mayor o igual a 7.0).***

* ***False: si el estudiante está reprobado (la nota final debe ser menor que 7.0).***

In [36]:
datos_alumnos['Aprobado_final'] = datos_alumnos['Notas_finales'].apply(lambda x: True if x >= 7.0 else False)
datos_alumnos

,Nombre,Edad,Nota,Aprobado,Puntos_extras,Notas_finales,Aprobado_final
0,Alberto,20,7.5,True,3.0,10.5,True
1,Ana,18,0.0,False,0.0,0.0,False
2,Camila,27,2.5,False,1.0,3.5,False
3,David,18,5.0,False,2.0,7.0,True
4,Brian,21,10.0,True,4.0,14.0,True
5,Bruna,23,0.0,False,0.0,0.0,False
6,Daniela,21,8.0,True,3.2,11.2,True
9,Victor,28,0.0,False,0.0,0.0,False
10,Danilo,21,0.0,False,0.0,0.0,False
11,Ignacio,24,4.5,False,1.8,6.3,False
12,Stephany,26,10.0,True,4.0,14.0,True
13,Miriam,25,9.0,True,3.6,12.6,True
14,Pablo,37,0.0,False,0.0,0.0,False
15,Milena,29,8.0,True,3.2,11.2,True
16,Lucas,33,0.0,False,0.0,0.0,False
17,Nadia,34,8.0,True,3.2,11.2,True

## **4. Realiza una selección y verifica qué estudiantes no habían sido aprobados anteriormente, pero ahora fueron aprobados después de sumar los puntos extras.**

In [37]:
alumnos_reprobados = datos_alumnos.query('Aprobado == False and Aprobado_final == True')
alumnos_reprobados

  Nombre  Edad  Nota  Aprobado  Puntos_extras  Notas_finales  Aprobado_final
3  David    18   5.0     False            2.0            7.0            True